version: '3.8'
services: 
  database:
    image: postgres:16-alpine3.18
    env_file:
      - ../.env
    ports: 
      - "52770:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 
    container_name: tabnews-database
    networks:
      - tabnews-network
networks:
  tabnews-network:
    driver: bridge
volumes:
  data:
